language: node_js
node_js:
- "node"

services:
  - "postgresql"
before_script:
  - psql -c 'create database nom_nom_test;' -U postgres
  - psql -c "create user nom_test_user WITH PASSWORD 'nom_test'" -U postgres

notifications: 
 email:
 on_success: never
 on_failure: always